# Generated by Django 5.2.7 on 2025-10-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi_link',
            field=models.URLField(blank=True, help_text='Optional: Full DOI URL (e.g., https://doi.org/10.xxxx/xxxxx)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, help_text='Optional: e.g., IEEE, Springer, ACM', max_length=200),
        ),
    ]
