# Generated by Django 5.2.7 on 2025-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_publication_doi_link_publication_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.FloatField(default=0.0, help_text='Enter your GPA or CGPA value (e.g., 3.8)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='grade_type',
            field=models.CharField(choices=[('cgpa', 'CGPA'), ('gpa', 'GPA')], default='cgpa', help_text='Select whether this is a CGPA or GPA', max_length=10),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conference',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
