# Generated by Django 5.2.7 on 2025-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF preferred)', null=True, upload_to='resumes/'),
        ),
    ]
