# Generated by Django 5.2.7 on 2025-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='items',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Python', help_text='e.g., Python, React, Docker', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Programming Languages'), ('frameworks', 'Frameworks & Libraries'), ('tools', 'Tools & Platforms'), ('databases', 'Databases'), ('cloud', 'Cloud & DevOps'), ('other', 'Other')], default='languages', max_length=20),
        ),
    ]
