# Generated by Django 5.2.7 on 2025-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_skill_items_skill_name_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Language', 'Programming Languages'), ('Frameworks', 'Frameworks & Libraries'), ('Front-End', 'Front-End'), ('Tools', 'Tools & Platforms'), ('Databases', 'Databases'), ('Cloud', 'Cloud & DevOps'), ('Concepts', 'Concepts & Methodologies'), ('Soft Skills', 'Soft Skills'), ('Hardware & Networking', 'Hardware & Networking'), ('Other', 'Other')], default='Language', max_length=30),
        ),
    ]
