# Generated by Django 5.2.7 on 2025-10-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problemsolving',
            name='rating',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
